# Detailed sample overview for classification with BioCLIP V1 and V2

In [1]:
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report

pd.set_option('display.max_columns', None)

In [2]:
path_1 ="/Users/krolik/Downloads/ultimate_bioclip_top1_rank_order_meta_12062025.csv"
path_2 = "/Users/krolik/Downloads/BioCLIP2_order_prediction.csv"
meta_b1 = pd.read_csv(path_1)
meta_b1

,Unnamed: 0.1,Unnamed: 0,path,name,size_bytes,width_px,height_px,blur_score,labels_set,image_id,label,two,partial,dirt,un,shadow,move,blur,camera,site,position,altitude,Month,Day,Hour,Minute,Second,day_time_bin,brightness_mean,brightness_std,dynamic_range,underexposed_pct,overexposed_pct,noise_estimate,edge_density,colorfulness,saturation_mean,saturation_std,distinct_hues,readable,day_night_twilight,dr_bin,file_name,top_1_rank_order,top_1_rank_score,rank_order_stimmt
0,0,0,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240820235954_crop_2.jpg,1310,73,74,103.1436,{'Diptera'},20240820235954_crop_2.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,20,23,59,54,night,174.8754,28.4967,87.00,0.000000,0.000740,6.1503,0.057201,82.6388,228.3221,11.7013,12,1,night,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.657524,0
1,1,1,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_blur_20240902222452_crop_0.jpg,3371,157,175,55.0449,"{'Diptera', 'blur'}",20240902222452_crop_0.jpg,Diptera,0,0,0,0,0,0,1,385,Weissfluhjoch,Upper,2540,9,2,22,24,52,night,194.6781,14.9224,39.00,0.000000,0.011975,4.4618,0.052630,77.4183,187.9203,33.2571,13,1,night,35.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_b...,Diptera,0.867665,0
2,2,2,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240904223209_crop_3.jpg,1627,78,89,149.6159,{'Diptera'},20240904223209_crop_3.jpg,Diptera,0,0,0,0,0,0,0,385,Weissfluhjoch,Upper,2540,9,4,22,32,9,night,151.6276,27.8872,90.95,0.004898,0.000000,7.1415,0.069865,66.0491,205.4160,16.5690,14,1,night,95.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.775668,0
3,3,3,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240806124033_crop_0.jpg,2015,95,114,58.4149,{'Diptera'},20240806124033_crop_0.jpg,Diptera,0,0,0,0,0,0,0,391,Monstein,Upper,2632,8,6,12,40,33,day,142.3081,34.6985,118.00,0.012650,0.000000,4.0915,0.041274,74.5807,221.5844,12.9128,11,1,day,115.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.522241,0
4,4,5,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240904232640_crop_0.jpg,1494,85,71,120.9880,{'Diptera'},20240904232640_crop_0.jpg,Diptera,0,0,0,0,0,0,0,383,Weissfluhjoch,Lower,1563,9,4,23,26,40,night,137.6406,26.3030,81.00,0.005965,0.000000,5.7140,0.068600,60.8455,211.0580,13.5109,13,1,night,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.867991,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39783,39783,48089,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240811111851_crop_0.jpg,1354,78,84,133.0929,{'Diptera'},20240811111851_crop_0.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,11,11,18,51,day,163.6148,25.3904,82.00,0.000000,0.000000,6.8268,0.050214,73.6332,213.9119,19.8772,15,1,day,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Coleoptera,0.924200,1
39784,39784,48090,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240826141946_crop_0.jpg,2491,127,123,227.6459,{'Diptera'},20240826141946_crop_0.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,26,14,19,46,day,161.1341,35.4737,117.00,0.001408,0.000000,8.5709,0.068434,86.1688,215.5665,23.3668,14,1,day,115.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.990932,0
39785,39785,48092,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240811184344_crop_1.jpg,1177,70,64,72.3144,{'Diptera'},20240811184344_crop_1.jpg,Diptera,0,0,0,0,0,0,0,387,Jatzhorn,Mid,2079,8,11,18,43,44,day,168.0027,19.2727,55.00,0.000000,0.000000,4.9522,0.042857,75.2217,239.0208,10.4238,8,1,day,55.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.897004,0
39786,39786,48093,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240821160704_crop_0.jpg,1405,96,83,42.6108,{'Diptera'},20240821160704_crop_0.jpg,Diptera,0,0,0,0,0,0,0,388,Jatzhorn,Upper,2463,8,21,16,7,4,day,170.2121,28.9970,94.00,0.000000,0.000000,3.5142,0.052585,73.7738,194.9290,17.7192,15,1,day,95.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.916924,0
39787,39787,48094,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240902135839_crop_1.jpg,1757,74,99,129.3498,{'Diptera'},20240902135839_crop_1.jpg,Diptera,0,0,0,0,0,0,0,391,Monstein,Upper,2632,9,2,13,58,39,day,148.6547,36.8961,127.75,0.003003,0.000000,5.6534,0.068387,78.7528,219.8355,13.7126,11,1,day,125.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.404499,0

In [6]:
meta_b1 = meta_b1.rename(columns={"top_1_rank_order":"bioclip_order",
                                  "top1_rank_score":"bioclip_order_score",
                                  "rank_order_stimmt":"bioclip_order_stimmt"
                                  })
meta_b1

,Unnamed: 0.1,Unnamed: 0,path,name,size_bytes,width_px,height_px,blur_score,labels_set,image_id,label,two,partial,dirt,un,shadow,move,blur,camera,site,position,altitude,Month,Day,Hour,Minute,Second,day_time_bin,brightness_mean,brightness_std,dynamic_range,underexposed_pct,overexposed_pct,noise_estimate,edge_density,colorfulness,saturation_mean,saturation_std,distinct_hues,readable,day_night_twilight,dr_bin,file_name,bioclip_order,top_1_rank_score,bioclip_order_stimmt
0,0,0,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240820235954_crop_2.jpg,1310,73,74,103.1436,{'Diptera'},20240820235954_crop_2.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,20,23,59,54,night,174.8754,28.4967,87.00,0.000000,0.000740,6.1503,0.057201,82.6388,228.3221,11.7013,12,1,night,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.657524,0
1,1,1,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_blur_20240902222452_crop_0.jpg,3371,157,175,55.0449,"{'Diptera', 'blur'}",20240902222452_crop_0.jpg,Diptera,0,0,0,0,0,0,1,385,Weissfluhjoch,Upper,2540,9,2,22,24,52,night,194.6781,14.9224,39.00,0.000000,0.011975,4.4618,0.052630,77.4183,187.9203,33.2571,13,1,night,35.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_b...,Diptera,0.867665,0
2,2,2,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240904223209_crop_3.jpg,1627,78,89,149.6159,{'Diptera'},20240904223209_crop_3.jpg,Diptera,0,0,0,0,0,0,0,385,Weissfluhjoch,Upper,2540,9,4,22,32,9,night,151.6276,27.8872,90.95,0.004898,0.000000,7.1415,0.069865,66.0491,205.4160,16.5690,14,1,night,95.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.775668,0
3,3,3,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240806124033_crop_0.jpg,2015,95,114,58.4149,{'Diptera'},20240806124033_crop_0.jpg,Diptera,0,0,0,0,0,0,0,391,Monstein,Upper,2632,8,6,12,40,33,day,142.3081,34.6985,118.00,0.012650,0.000000,4.0915,0.041274,74.5807,221.5844,12.9128,11,1,day,115.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.522241,0
4,4,5,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240904232640_crop_0.jpg,1494,85,71,120.9880,{'Diptera'},20240904232640_crop_0.jpg,Diptera,0,0,0,0,0,0,0,383,Weissfluhjoch,Lower,1563,9,4,23,26,40,night,137.6406,26.3030,81.00,0.005965,0.000000,5.7140,0.068600,60.8455,211.0580,13.5109,13,1,night,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.867991,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39783,39783,48089,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240811111851_crop_0.jpg,1354,78,84,133.0929,{'Diptera'},20240811111851_crop_0.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,11,11,18,51,day,163.6148,25.3904,82.00,0.000000,0.000000,6.8268,0.050214,73.6332,213.9119,19.8772,15,1,day,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Coleoptera,0.924200,1
39784,39784,48090,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240826141946_crop_0.jpg,2491,127,123,227.6459,{'Diptera'},20240826141946_crop_0.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,26,14,19,46,day,161.1341,35.4737,117.00,0.001408,0.000000,8.5709,0.068434,86.1688,215.5665,23.3668,14,1,day,115.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.990932,0
39785,39785,48092,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240811184344_crop_1.jpg,1177,70,64,72.3144,{'Diptera'},20240811184344_crop_1.jpg,Diptera,0,0,0,0,0,0,0,387,Jatzhorn,Mid,2079,8,11,18,43,44,day,168.0027,19.2727,55.00,0.000000,0.000000,4.9522,0.042857,75.2217,239.0208,10.4238,8,1,day,55.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.897004,0
39786,39786,48093,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240821160704_crop_0.jpg,1405,96,83,42.6108,{'Diptera'},20240821160704_crop_0.jpg,Diptera,0,0,0,0,0,0,0,388,Jatzhorn,Upper,2463,8,21,16,7,4,day,170.2121,28.9970,94.00,0.000000,0.000000,3.5142,0.052585,73.7738,194.9290,17.7192,15,1,day,95.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.916924,0
39787,39787,48094,/Users/krolik/Documents/python_/MScThesis/diop...,Diptera_20240902135839_crop_1.jpg,1757,74,99,129.3498,{'Diptera'},20240902135839_crop_1.jpg,Diptera,0,0,0,0,0,0,0,391,Monstein,Upper,2632,9,2,13,58,39,day,148.6547,36.8961,127.75,0.003003,0.000000,5.6534,0.068387,78.7528,219.8355,13.7126,11,1,day,125.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.404499,0

In [7]:
def split_on_number(s):
    parts = s.split('_')
    for i, p in enumerate(parts):
        if p and p[0].isdigit():
            return set(parts[:i]), '_'.join(parts[i:])
    return set(parts), ''

In [8]:
bioclip2 = pd.read_csv(path_2)
bioclip2[['labels_set', 'image_id']] = bioclip2['file_name'].apply(
    lambda s: pd.Series(split_on_number(s))
)
bioclip2

,file_name,kingdom,phylum,class,order,score,labels_set,image_id
0,/Users/shaky/Lena/ALL_copy/Diptera_20240820235...,Animalia,Arthropoda,Insecta,Diptera,0.922500,"{/Users/shaky/Lena/ALL, copy/Diptera}",20240820235954_crop_2.jpg
1,/Users/shaky/Lena/ALL_copy/Diptera_blur_202409...,Animalia,Arthropoda,Insecta,Diptera,0.988445,"{/Users/shaky/Lena/ALL, blur, copy/Diptera}",20240902222452_crop_0.jpg
2,/Users/shaky/Lena/ALL_copy/Diptera_20240904223...,Animalia,Arthropoda,Insecta,Diptera,0.942936,"{/Users/shaky/Lena/ALL, copy/Diptera}",20240904223209_crop_3.jpg
3,/Users/shaky/Lena/ALL_copy/Diptera_20240806124...,Animalia,Arthropoda,Insecta,Diptera,0.847152,"{/Users/shaky/Lena/ALL, copy/Diptera}",20240806124033_crop_0.jpg
4,/Users/shaky/Lena/ALL_copy/partial_20240816221...,Animalia,Arthropoda,Insecta,Lepidoptera,0.687838,"{/Users/shaky/Lena/ALL, copy/partial}",20240816221624_crop_0.jpg
...,...,...,...,...,...,...,...,...
48095,/Users/shaky/Lena/ALL_copy/un_20240829170452_c...,Animalia,Arthropoda,Insecta,Hemiptera,0.889910,"{/Users/shaky/Lena/ALL, copy/un}",20240829170452_crop_0.jpg
48096,/Users/shaky/Lena/ALL_copy/Diptera_20240811184...,Animalia,Arthropoda,Insecta,Diptera,0.573388,"{/Users/shaky/Lena/ALL, copy/Diptera}",20240811184344_crop_1.jpg
48097,/Users/shaky/Lena/ALL_copy/Diptera_20240821160...,Animalia,Arthropoda,Insecta,Diptera,0.932921,"{/Users/shaky/Lena/ALL, copy/Diptera}",20240821160704_crop_0.jpg
48098,/Users/shaky/Lena/ALL_copy/Diptera_20240902135...,Animalia,Arthropoda,Insecta,Diptera,0.975471,"{/Users/shaky/Lena/ALL, copy/Diptera}",20240902135839_crop_1.jpg
48099,/Users/shaky/Lena/ALL_copy/partial_20240831095...,Animalia,Arthropoda,Insecta,Diptera,0.976570,"{/Users/shaky/Lena/ALL, copy/partial}",20240831095805_crop_0.jpg

In [10]:
bioclip2 = bioclip2.rename(columns={"kingdom": "b2_kingdom",
                                    "class":"b2_class",
                                    "order":"b2_order",
                                    "score":"b2_score"})
bioclip2 = bioclip2.drop(columns=['file_name','labels_set'])
bioclip2

,b2_kingdom,phylum,b2_class,b2_order,b2_score,image_id
0,Animalia,Arthropoda,Insecta,Diptera,0.922500,20240820235954_crop_2.jpg
1,Animalia,Arthropoda,Insecta,Diptera,0.988445,20240902222452_crop_0.jpg
2,Animalia,Arthropoda,Insecta,Diptera,0.942936,20240904223209_crop_3.jpg
3,Animalia,Arthropoda,Insecta,Diptera,0.847152,20240806124033_crop_0.jpg
4,Animalia,Arthropoda,Insecta,Lepidoptera,0.687838,20240816221624_crop_0.jpg
...,...,...,...,...,...,...
48095,Animalia,Arthropoda,Insecta,Hemiptera,0.889910,20240829170452_crop_0.jpg
48096,Animalia,Arthropoda,Insecta,Diptera,0.573388,20240811184344_crop_1.jpg
48097,Animalia,Arthropoda,Insecta,Diptera,0.932921,20240821160704_crop_0.jpg
48098,Animalia,Arthropoda,Insecta,Diptera,0.975471,20240902135839_crop_1.jpg
48099,Animalia,Arthropoda,Insecta,Diptera,0.976570,20240831095805_crop_0.jpg

In [12]:
meta_b1b2 = meta_b1.merge(bioclip2, how='left', on='image_id')
meta_b1b2 = meta_b1b2.drop(columns=['Unnamed: 0.1','Unnamed: 0','path'])
meta_b1b2['b2_order_stimmt']= [1 if meta_b1b2['label'][i]==meta_b1b2['b2_order'][i] else 0 for i in range(meta_b1b2.shape[0])]
meta_b1b2

,name,size_bytes,width_px,height_px,blur_score,labels_set,image_id,label,two,partial,dirt,un,shadow,move,blur,camera,site,position,altitude,Month,Day,Hour,Minute,Second,day_time_bin,brightness_mean,brightness_std,dynamic_range,underexposed_pct,overexposed_pct,noise_estimate,edge_density,colorfulness,saturation_mean,saturation_std,distinct_hues,readable,day_night_twilight,dr_bin,file_name,bioclip_order,top_1_rank_score,bioclip_order_stimmt,b2_kingdom,phylum,b2_class,b2_order,b2_score,b2_order_stimmt
0,Diptera_20240820235954_crop_2.jpg,1310,73,74,103.1436,{'Diptera'},20240820235954_crop_2.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,20,23,59,54,night,174.8754,28.4967,87.00,0.000000,0.000740,6.1503,0.057201,82.6388,228.3221,11.7013,12,1,night,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.657524,0,Animalia,Arthropoda,Insecta,Diptera,0.922500,1
1,Diptera_blur_20240902222452_crop_0.jpg,3371,157,175,55.0449,"{'Diptera', 'blur'}",20240902222452_crop_0.jpg,Diptera,0,0,0,0,0,0,1,385,Weissfluhjoch,Upper,2540,9,2,22,24,52,night,194.6781,14.9224,39.00,0.000000,0.011975,4.4618,0.052630,77.4183,187.9203,33.2571,13,1,night,35.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_b...,Diptera,0.867665,0,Animalia,Arthropoda,Insecta,Diptera,0.988445,1
2,Diptera_20240904223209_crop_3.jpg,1627,78,89,149.6159,{'Diptera'},20240904223209_crop_3.jpg,Diptera,0,0,0,0,0,0,0,385,Weissfluhjoch,Upper,2540,9,4,22,32,9,night,151.6276,27.8872,90.95,0.004898,0.000000,7.1415,0.069865,66.0491,205.4160,16.5690,14,1,night,95.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.775668,0,Animalia,Arthropoda,Insecta,Diptera,0.942936,1
3,Diptera_20240806124033_crop_0.jpg,2015,95,114,58.4149,{'Diptera'},20240806124033_crop_0.jpg,Diptera,0,0,0,0,0,0,0,391,Monstein,Upper,2632,8,6,12,40,33,day,142.3081,34.6985,118.00,0.012650,0.000000,4.0915,0.041274,74.5807,221.5844,12.9128,11,1,day,115.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.522241,0,Animalia,Arthropoda,Insecta,Diptera,0.847152,1
4,Diptera_20240904232640_crop_0.jpg,1494,85,71,120.9880,{'Diptera'},20240904232640_crop_0.jpg,Diptera,0,0,0,0,0,0,0,383,Weissfluhjoch,Lower,1563,9,4,23,26,40,night,137.6406,26.3030,81.00,0.005965,0.000000,5.7140,0.068600,60.8455,211.0580,13.5109,13,1,night,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.867991,0,Animalia,Arthropoda,Insecta,Diptera,0.582776,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39783,Diptera_20240811111851_crop_0.jpg,1354,78,84,133.0929,{'Diptera'},20240811111851_crop_0.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,11,11,18,51,day,163.6148,25.3904,82.00,0.000000,0.000000,6.8268,0.050214,73.6332,213.9119,19.8772,15,1,day,85.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Coleoptera,0.924200,1,Animalia,Arthropoda,Insecta,Diptera,0.768027,1
39784,Diptera_20240826141946_crop_0.jpg,2491,127,123,227.6459,{'Diptera'},20240826141946_crop_0.jpg,Diptera,0,0,0,0,0,0,0,384,Weissfluhjoch,Mid,2102,8,26,14,19,46,day,161.1341,35.4737,117.00,0.001408,0.000000,8.5709,0.068434,86.1688,215.5665,23.3668,14,1,day,115.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.990932,0,Animalia,Arthropoda,Insecta,Diptera,0.990265,1
39785,Diptera_20240811184344_crop_1.jpg,1177,70,64,72.3144,{'Diptera'},20240811184344_crop_1.jpg,Diptera,0,0,0,0,0,0,0,387,Jatzhorn,Mid,2079,8,11,18,43,44,day,168.0027,19.2727,55.00,0.000000,0.000000,4.9522,0.042857,75.2217,239.0208,10.4238,8,1,day,55.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.897004,0,Animalia,Arthropoda,Insecta,Diptera,0.573388,1
39786,Diptera_20240821160704_crop_0.jpg,1405,96,83,42.6108,{'Diptera'},20240821160704_crop_0.jpg,Diptera,0,0,0,0,0,0,0,388,Jatzhorn,Upper,2463,8,21,16,7,4,day,170.2121,28.9970,94.00,0.000000,0.000000,3.5142,0.052585,73.7738,194.9290,17.7192,15,1,day,95.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.916924,0,Animalia,Arthropoda,Insecta,Diptera,0.932921,1
39787,Diptera_20240902135839_crop_1.jpg,1757,74,99,129.3498,{'Diptera'},20240902135839_crop_1.jpg,Diptera,0,0,0,0,0,0,0,391,Monstein,Upper,2632,9,2,13,58,39,day,148.6547,36.8961,127.75,0.003003,0.000000,5.6534,0.068387,78.7528,219.8355,13.7126,11,1,day,125.0,/Users/shaky/Downloads/Lena/ALL_copy/Diptera_2...,Diptera,0.404499,0,Animalia,Arthropoda,Insecta,Diptera,0.975471,1

In [13]:
def diagnostic_tables(df, true_col="label", pred_col="order_pred",
                     collapse_unknown_preds=True):
    """
    Returns three tables:
      - counts: raw confusion matrix (true rows × predicted columns)
      - recall_pct: row-normalised confusion matrix (each row sums to 100%)
      - metrics: per-class precision, recall, F1, support
    """
    # The set of "real" classes is determined by the true labels
    true_classes = sorted(df[true_col].unique())

    if collapse_unknown_preds:
        # Map any predicted class not in true_classes to "<other>"
        # Useful for BioCLIP's unconstrained predictions
        df = df.copy()
        df[pred_col] = df[pred_col].where(
            df[pred_col].isin(true_classes), other="<other>"
        )
        pred_classes = true_classes + ["<other>"]
    else:
        pred_classes = sorted(df[pred_col].unique())

    # 1. Raw counts
    cm = confusion_matrix(df[true_col], df[pred_col], labels=pred_classes)
    # confusion_matrix uses 'labels' for both axes; restrict rows to true classes
    counts = pd.DataFrame(cm, index=pred_classes, columns=pred_classes)
    counts = counts.loc[true_classes, :]  # rows = actual true classes only
    counts.index.name = "true"
    counts.columns.name = "predicted"

    # 2. Row-normalised (per-class recall view)
    recall_pct = counts.div(counts.sum(axis=1), axis=0) * 100
    recall_pct = recall_pct.round(1)

    # 3. Per-class metrics
    report = classification_report(
        df[true_col], df[pred_col],
        labels=true_classes,         # restrict to real classes for precision/recall
        zero_division=0,
        output_dict=True,
    )
    metrics = pd.DataFrame(report).T
    metrics = metrics.loc[true_classes + ["macro avg", "weighted avg"]]
    metrics["support"] = metrics["support"].astype(int)
    metrics = metrics.round(3)

    return counts, recall_pct, metrics

In [16]:
b1_readable = meta_b1b2[meta_b1b2['readable']==1][['label','bioclip_order']].copy()
b1_readable = b1_readable.rename(columns={'bioclip_order':'order_pred'})
b1_readable

         label  order_pred
0      Diptera     Diptera
1      Diptera     Diptera
2      Diptera     Diptera
3      Diptera     Diptera
4      Diptera     Diptera
...        ...         ...
39783  Diptera  Coleoptera
39784  Diptera     Diptera
39785  Diptera     Diptera
39786  Diptera     Diptera
39787  Diptera     Diptera

[39788 rows x 2 columns]

In [18]:

# --- Usage ---
counts_b1, recall_pct_b1, metrics_b1 = diagnostic_tables(b1_readable)

print("Raw counts:")
print(counts_b1)
print("\nRow-normalised (% of true class):")
print(recall_pct_b1)
print("\nPer-class metrics:")
print(metrics_b1)

Raw counts:
predicted      Araneae  Blattodea  Coleoptera  Diptera  Hemiptera  \
true
Araneae            532          0           8        1          9
Blattodea            0          8           5        0          2
Coleoptera           1          0         700      170        124
Diptera            389          0        4016    23717       2074
Hemiptera           14          0          98      315        236
Hymenoptera         56         13         697      129        360
Ixodida              1          0           0        0          0
Lepidoptera          2          0          10       11         33
Mecoptera            0          0           1       13          8
Neuroptera           0          1           8       53         22
Orthoptera           0          0           0        0          0
Plecoptera           0          0           0        1          5
Raphidioptera        0          0           0        0          0
Trichoptera          0          0           2        0          0

predicted      Hymenoptera  Ixodida  Lepidoptera  Mecoptera  Neuroptera  \
true
Araneae                  8        2            0          0           0
Blattodea                0        0            2          0           1
Coleoptera              37        9            3          0           1
Diptera                371       58          102         12          55
Hemiptera               12        1           11          0           0
Hymenoptera           1748        0           43          5           3
Ixodida                  0        0            0          0           0
Lepidoptera              3        0         1646          0           3
Mecoptera                1        0            0          3           2
Neuroptera               0        0            5          0           8
Orthoptera               0        0            0          0           0
Plecoptera               0        0            0          0           0
Raphidioptera            0        0            0          0           0
Trichoptera              0        0            0          0           0

predicted      Orthoptera  Plecoptera  Raphidioptera  Trichoptera  <other>
true
Araneae                 0           0              0            0        4
Blattodea               2           0              0            2        1
Coleoptera              4           0              0            0       94
Diptera                50           4              7           75      984
Hemiptera               5           0              0            1       82
Hymenoptera             7          14              1           24      226
Ixodida                 0           0              0            0        0
Lepidoptera             0           0              0           23       13
Mecoptera               2           0              0            3        1
Neuroptera              1           0              0            2       15
Orthoptera              8           0              0            0        0
Plecoptera              0          42              2            1        3
Raphidioptera           0           0              2            0        0
Trichoptera             0           0              0           83        0

Row-normalised (% of true class):
predicted      Araneae  Blattodea  Coleoptera  Diptera  Hemiptera  \
true
Araneae           94.3        0.0         1.4      0.2        1.6
Blattodea          0.0       34.8        21.7      0.0        8.7
Coleoptera         0.1        0.0        61.2     14.9       10.8
Diptera            1.2        0.0        12.6     74.3        6.5
Hemiptera          1.8        0.0        12.6     40.6       30.5
Hymenoptera        1.7        0.4        21.0      3.9       10.8
Ixodida          100.0        0.0         0.0      0.0        0.0
Lepidoptera        0.1        0.0         0.6      0.6        1.9
Mecoptera          0.0        0.0         2.9     38.2       23.5
Neuroptera         0.0        0.9         7.0     46.1       19.1
Orthoptera         0.0        0.0         0.0      0.0        0.0
Plecoptera         0.0        0.0         0.0      1.9        9.3
Raphidioptera      0.0        0.0         0.0      0.0        0.0
Trichoptera        0.0        0.0         2.4      0.0        0.0

predicted      Hymenoptera  Ixodida  Lepidoptera  Mecoptera  Neuroptera  \
true
Araneae                1.4      0.4          0.0        0.0         0.0
Blattodea              0.0      0.0          8.7        0.0         4.3
Coleoptera             3.2      0.8          0.3        0.0         0.1
Diptera                1.2      0.2          0.3        0.0         0.2
Hemiptera              1.5      0.1          1.4        0.0         0.0
Hymenoptera           52.6      0.0          1.3        0.2         0.1
Ixodida                0.0      0.0          0.0        0.0         0.0
Lepidoptera            0.2      0.0         94.4        0.0         0.2
Mecoptera              2.9      0.0          0.0        8.8         5.9
Neuroptera             0.0      0.0          4.3        0.0         7.0
Orthoptera             0.0      0.0          0.0        0.0         0.0
Plecoptera             0.0      0.0          0.0        0.0         0.0
Raphidioptera          0.0      0.0          0.0        0.0         0.0
Trichoptera            0.0      0.0          0.0        0.0         0.0

predicted      Orthoptera  Plecoptera  Raphidioptera  Trichoptera  <other>
true
Araneae               0.0         0.0            0.0          0.0      0.7
Blattodea             8.7         0.0            0.0          8.7      4.3
Coleoptera            0.3         0.0            0.0          0.0      8.2
Diptera               0.2         0.0            0.0          0.2      3.1
Hemiptera             0.6         0.0            0.0          0.1     10.6
Hymenoptera           0.2         0.4            0.0          0.7      6.8
Ixodida               0.0         0.0            0.0          0.0      0.0
Lepidoptera           0.0         0.0            0.0          1.3      0.7
Mecoptera             5.9         0.0            0.0          8.8      2.9
Neuroptera            0.9         0.0            0.0          1.7     13.0
Orthoptera          100.0         0.0            0.0          0.0      0.0
Plecoptera            0.0        77.8            3.7          1.9      5.6
Raphidioptera         0.0         0.0          100.0          0.0      0.0
Trichoptera           0.0         0.0            0.0         97.6      0.0

Per-class metrics:
               precision  recall  f1-score  support
Araneae            0.535   0.943     0.682      564
Blattodea          0.364   0.348     0.356       23
Coleoptera         0.126   0.612     0.209     1143
Diptera            0.972   0.743     0.842    31914
Hemiptera          0.082   0.305     0.129      775
Hymenoptera        0.802   0.526     0.635     3326
Ixodida            0.000   0.000     0.000        1
Lepidoptera        0.908   0.944     0.926     1744
Mecoptera          0.150   0.088     0.111       34
Neuroptera         0.110   0.070     0.085      115
Orthoptera         0.101   1.000     0.184        8
Plecoptera         0.700   0.778     0.737       54
Raphidioptera      0.167   1.000     0.286        2
Trichoptera        0.388   0.976     0.555       85
macro avg          0.386   0.595     0.410    39788
weighted avg       0.901   0.722     0.790    39788

In [21]:
counts_b1.to_csv("/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/sample_description/counts_b1.csv")
recall_pct_b1.to_csv("/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/sample_description/recall_pct_b1.csv")
metrics_b1.to_csv("/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/sample_description/metrics_b1.csv")

# bioCLIP2

In [19]:
b2_readable = meta_b1b2[meta_b1b2['readable']==1][['label','b2_order']].copy()
b2_readable = b2_readable.rename(columns={'b2_order':'order_pred'})
b2_readable

         label order_pred
0      Diptera    Diptera
1      Diptera    Diptera
2      Diptera    Diptera
3      Diptera    Diptera
4      Diptera    Diptera
...        ...        ...
39783  Diptera    Diptera
39784  Diptera    Diptera
39785  Diptera    Diptera
39786  Diptera    Diptera
39787  Diptera    Diptera

[39788 rows x 2 columns]

In [20]:
counts_b2, recall_pct_b2, metrics_b2 = diagnostic_tables(b2_readable)

print("Raw counts:")
print(counts_b2)
print("\nRow-normalised (% of true class):")
print(recall_pct_b2)
print("\nPer-class metrics:")
print(metrics_b2)

Raw counts:
predicted      Araneae  Blattodea  Coleoptera  Diptera  Hemiptera  \
true
Araneae            553          0           4        1          0
Blattodea            0         19           1        0          3
Coleoptera           9          0         647       74        214
Diptera             24        132        1154    26885       2945
Hemiptera            4          3          44       98        480
Hymenoptera          3          2         137      159        208
Ixodida              1          0           0        0          0
Lepidoptera          0          0           2        5          6
Mecoptera            0          0           0       15          0
Neuroptera           0          0           2        8         51
Orthoptera           0          0           0        0          0
Plecoptera           0          0           0        0          0
Raphidioptera        0          0           0        0          0
Trichoptera          0          0           2        0          2

predicted      Hymenoptera  Ixodida  Lepidoptera  Mecoptera  Neuroptera  \
true
Araneae                  5        0            0          0           0
Blattodea                0        0            0          0           0
Coleoptera              50        0            7          0           0
Diptera                214        3          216          0          17
Hemiptera                6        1           16          0           0
Hymenoptera           2643        0            5          0           6
Ixodida                  0        0            0          0           0
Lepidoptera              1        0         1718          0           3
Mecoptera               16        0            0          2           0
Neuroptera               1        0           13          0          12
Orthoptera               0        0            0          0           0
Plecoptera               5        0            0          0           0
Raphidioptera            0        0            0          0           0
Trichoptera              1        0            6          0           3

predicted      Orthoptera  Plecoptera  Raphidioptera  Trichoptera  <other>
true
Araneae                 0           0              0            0        1
Blattodea               0           0              0            0        0
Coleoptera              2           0              0            0      140
Diptera                95           1              0            7      221
Hemiptera              53           0              0            1       69
Hymenoptera             2           3              0            2      156
Ixodida                 0           0              0            0        0
Lepidoptera             0           1              0            7        1
Mecoptera               0           0              0            0        1
Neuroptera              0           1              0            0       27
Orthoptera              8           0              0            0        0
Plecoptera              0          49              0            0        0
Raphidioptera           0           0              2            0        0
Trichoptera             0           2              0           69        0

Row-normalised (% of true class):
predicted      Araneae  Blattodea  Coleoptera  Diptera  Hemiptera  \
true
Araneae           98.0        0.0         0.7      0.2        0.0
Blattodea          0.0       82.6         4.3      0.0       13.0
Coleoptera         0.8        0.0        56.6      6.5       18.7
Diptera            0.1        0.4         3.6     84.2        9.2
Hemiptera          0.5        0.4         5.7     12.6       61.9
Hymenoptera        0.1        0.1         4.1      4.8        6.3
Ixodida          100.0        0.0         0.0      0.0        0.0
Lepidoptera        0.0        0.0         0.1      0.3        0.3
Mecoptera          0.0        0.0         0.0     44.1        0.0
Neuroptera         0.0        0.0         1.7      7.0       44.3
Orthoptera         0.0        0.0         0.0      0.0        0.0
Plecoptera         0.0        0.0         0.0      0.0        0.0
Raphidioptera      0.0        0.0         0.0      0.0        0.0
Trichoptera        0.0        0.0         2.4      0.0        2.4

predicted      Hymenoptera  Ixodida  Lepidoptera  Mecoptera  Neuroptera  \
true
Araneae                0.9      0.0          0.0        0.0         0.0
Blattodea              0.0      0.0          0.0        0.0         0.0
Coleoptera             4.4      0.0          0.6        0.0         0.0
Diptera                0.7      0.0          0.7        0.0         0.1
Hemiptera              0.8      0.1          2.1        0.0         0.0
Hymenoptera           79.5      0.0          0.2        0.0         0.2
Ixodida                0.0      0.0          0.0        0.0         0.0
Lepidoptera            0.1      0.0         98.5        0.0         0.2
Mecoptera             47.1      0.0          0.0        5.9         0.0
Neuroptera             0.9      0.0         11.3        0.0        10.4
Orthoptera             0.0      0.0          0.0        0.0         0.0
Plecoptera             9.3      0.0          0.0        0.0         0.0
Raphidioptera          0.0      0.0          0.0        0.0         0.0
Trichoptera            1.2      0.0          7.1        0.0         3.5

predicted      Orthoptera  Plecoptera  Raphidioptera  Trichoptera  <other>
true
Araneae               0.0         0.0            0.0          0.0      0.2
Blattodea             0.0         0.0            0.0          0.0      0.0
Coleoptera            0.2         0.0            0.0          0.0     12.2
Diptera               0.3         0.0            0.0          0.0      0.7
Hemiptera             6.8         0.0            0.0          0.1      8.9
Hymenoptera           0.1         0.1            0.0          0.1      4.7
Ixodida               0.0         0.0            0.0          0.0      0.0
Lepidoptera           0.0         0.1            0.0          0.4      0.1
Mecoptera             0.0         0.0            0.0          0.0      2.9
Neuroptera            0.0         0.9            0.0          0.0     23.5
Orthoptera          100.0         0.0            0.0          0.0      0.0
Plecoptera            0.0        90.7            0.0          0.0      0.0
Raphidioptera         0.0         0.0          100.0          0.0      0.0
Trichoptera           0.0         2.4            0.0         81.2      0.0

Per-class metrics:
               precision  recall  f1-score  support
Araneae            0.931   0.980     0.955      564
Blattodea          0.122   0.826     0.212       23
Coleoptera         0.325   0.566     0.413     1143
Diptera            0.987   0.842     0.909    31914
Hemiptera          0.123   0.619     0.205      775
Hymenoptera        0.898   0.795     0.843     3326
Ixodida            0.000   0.000     0.000        1
Lepidoptera        0.867   0.985     0.922     1744
Mecoptera          1.000   0.059     0.111       34
Neuroptera         0.293   0.104     0.154      115
Orthoptera         0.050   1.000     0.095        8
Plecoptera         0.860   0.907     0.883       54
Raphidioptera      1.000   1.000     1.000        2
Trichoptera        0.802   0.812     0.807       85
macro avg          0.590   0.678     0.536    39788
weighted avg       0.934   0.832     0.873    39788

In [22]:
counts_b2.to_csv("/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/sample_description/counts_b2.csv")
recall_pct_b2.to_csv("/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/sample_description/recall_pct_b2.csv")
metrics_b2.to_csv("/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/sample_description/metrics_b2.csv")

# Pre-processing

In [28]:
path_meta_df = "/Users/krolik/Downloads/Thesis/detailed_sample_description/meta.csv"
meta = pd.read_csv(path_meta_df)

### unsharp

In [36]:
unsharp_current_all_path = "/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/preprocessing/order/last_attempt_full_run/bioclip_order_unsharp_current_preprocessed_all.csv"

unsharp_current_all = pd.read_csv(unsharp_current_all_path)
unsharp_current_all = unsharp_current_all.drop(columns=['kingdom','phylum','class'])
unsharp_current_all[['labels_set', 'image_id']] = unsharp_current_all['file_name'].apply(
    lambda s: pd.Series(split_on_number(s))
)

unsharp_current_all = unsharp_current_all.rename(columns={'order':'order_redone','score':'score_redone'}).drop(columns=['labels_set'])
unsharp_current_all = unsharp_current_all.merge(meta,on='image_id', how='left')
unsharp_current_all['rank_order_stimmt_redo'] = [0 if unsharp_current_all['order_redone'][i]==unsharp_current_all['label'][i] else 1 for i in range(unsharp_current_all.shape[0])]
print('all:', unsharp_current_all['rank_order_stimmt_redo'].value_counts())

all: rank_order_stimmt_redo
0    29325
1    10457
Name: count, dtype: int64

In [38]:
unsharp_per_order = unsharp_current_all.groupby("label").agg(
    n=("score", "size"),
    n_misclassified=("rank_order_stimmt", "sum"),
    n_rescued=("rank_order_stimmt_redo", 
                lambda x: ((unsharp_current_all.loc[x.index, "rank_order_stimmt"] == 1) & 
                            (x == 0)).sum()),
    n_damaged=("rank_order_stimmt_redo", 
                lambda x: ((unsharp_current_all.loc[x.index, "rank_order_stimmt"] == 0) & 
                            (x == 1)).sum()),
)
unsharp_per_order["net"] = unsharp_per_order["n_rescued"] - unsharp_per_order["n_damaged"]
unsharp_per_order["original_error_rate"] = unsharp_per_order["n_misclassified"] / unsharp_per_order["n"]
unsharp_per_order["new_error_rate"] = (unsharp_per_order["n_misclassified"] - unsharp_per_order["n_rescued"] 
                                + unsharp_per_order["n_damaged"]) / unsharp_per_order["n"]
print("Unsharp\n", unsharp_per_order.sort_values("label", ascending=True))

Unsharp
                    n  n_misclassified  n_rescued  n_damaged  net  \
label
Araneae          564               32          4         30  -26
Blattodea         23               15          0          5   -5
Coleoptera      1142              442        114        157  -43
Diptera        31911             8197       2858       2317  541
Hemiptera        775              539         91        111  -20
Hymenoptera     3324             1577        501        269  232
Ixodida            1                1          0          0    0
Lepidoptera     1744               98         23         84  -61
Mecoptera         34               31          2          0    2
Neuroptera       115              107          1          2   -1
Orthoptera         8                0          0          0    0
Plecoptera        54               12          2          6   -4
Raphidioptera      2                0          0          1   -1
Trichoptera       85                2          1         19  -18

               original_error_rate  new_error_rate
label
Araneae                   0.056738        0.102837
Blattodea                 0.652174        0.869565
Coleoptera                0.387040        0.424694
Diptera                   0.256871        0.239917
Hemiptera                 0.695484        0.721290
Hymenoptera               0.474428        0.404633
Ixodida                   1.000000        1.000000
Lepidoptera               0.056193        0.091170
Mecoptera                 0.911765        0.852941
Neuroptera                0.930435        0.939130
Orthoptera                0.000000        0.000000
Plecoptera                0.222222        0.296296
Raphidioptera             0.000000        0.500000
Trichoptera               0.023529        0.235294

In [39]:
unsharp_per_order.to_csv("/Users/krolik/Downloads/Thesis/detailed_sample_description/rescue_damage_unsharp.csv")

### Denosing

In [29]:
denoising_all_path = "/Users/krolik/Documents/python_/MScThesis/diopsis_apollo_all/md/preprocessing/order/last_attempt_full_run/bioclip_order_denoising_preprocessed_all3.csv"

denoising_all = pd.read_csv(denoising_all_path)
denoising_all = denoising_all.drop(columns=['kingdom','phylum','class'])
denoising_all[['labels_set', 'image_id']] = denoising_all['file_name'].apply(
    lambda s: pd.Series(split_on_number(s))
)

denoising_all = denoising_all.rename(columns={'order':'order_redone','score':'score_redone'}).drop(columns=['labels_set'])
denoising_all = denoising_all.merge(meta,on='image_id', how='left')
denoising_all['rank_order_stimmt_redo'] = [0 if denoising_all['order_redone'][i]==denoising_all['label'][i] else 1 for i in range(denoising_all.shape[0])]
print('all:', denoising_all['rank_order_stimmt_redo'].value_counts())

all: rank_order_stimmt_redo
0    23338
1    16444
Name: count, dtype: int64

In [30]:
per_order_denoising = denoising_all.groupby("label").agg(
    n=("score", "size"),
    n_misclassified=("rank_order_stimmt", "sum"),
    n_rescued=("rank_order_stimmt_redo", 
                lambda x: ((denoising_all.loc[x.index, "rank_order_stimmt"] == 1) & 
                            (x == 0)).sum()),
    n_damaged=("rank_order_stimmt_redo", 
                lambda x: ((denoising_all.loc[x.index, "rank_order_stimmt"] == 0) & 
                            (x == 1)).sum()),
)
per_order_denoising["net"] = per_order_denoising["n_rescued"] - per_order_denoising["n_damaged"]
per_order_denoising["original_error_rate"] = per_order_denoising["n_misclassified"] / per_order_denoising["n"]
per_order_denoising["new_error_rate"] = (per_order_denoising["n_misclassified"] - per_order_denoising["n_rescued"] 
                                + per_order_denoising["n_damaged"]) / per_order_denoising["n"]
print("Denoising\n", per_order_denoising.sort_values("label", ascending=True))

Denoising
                    n  n_misclassified  n_rescued  n_damaged   net  \
label
Araneae          564               32          2        109  -107
Blattodea         23               15          7          1     6
Coleoptera      1142              442        129        347  -218
Diptera        31911             8197       3495       7057 -3562
Hemiptera        775              539         16        213  -197
Hymenoptera     3324             1577         83       1229 -1146
Ixodida            1                1          0          0     0
Lepidoptera     1744               98         38         78   -40
Mecoptera         34               31          0          2    -2
Neuroptera       115              107          0          6    -6
Orthoptera         8                0          0          0     0
Plecoptera        54               12          0         41   -41
Raphidioptera      2                0          0          2    -2
Trichoptera       85                2          1         77   -76

               original_error_rate  new_error_rate
label
Araneae                   0.056738        0.246454
Blattodea                 0.652174        0.391304
Coleoptera                0.387040        0.577933
Diptera                   0.256871        0.368494
Hemiptera                 0.695484        0.949677
Hymenoptera               0.474428        0.819194
Ixodida                   1.000000        1.000000
Lepidoptera               0.056193        0.079128
Mecoptera                 0.911765        0.970588
Neuroptera                0.930435        0.982609
Orthoptera                0.000000        0.000000
Plecoptera                0.222222        0.981481
Raphidioptera             0.000000        1.000000
Trichoptera               0.023529        0.917647

In [31]:
per_order_denoising.to_csv("/Users/krolik/Downloads/Thesis/detailed_sample_description/rescue_damage_denoising.csv")

### gamma

In [32]:
gamma_path="/Users/krolik/Downloads/Thesis/detailed_sample_description/bioclip_order_gamma2_preprocessed_all.csv"

gamma_all = pd.read_csv(gamma_path)
gamma_all = gamma_all.drop(columns=['kingdom','phylum','class'])
gamma_all[['labels_set', 'image_id']] = gamma_all['file_name'].apply(
    lambda s: pd.Series(split_on_number(s))
)

gamma_all = gamma_all.rename(columns={'order':'order_redone','score':'score_redone'}).drop(columns=['labels_set'])
gamma_all = gamma_all.merge(meta,on='image_id', how='left')
gamma_all['rank_order_stimmt_redo'] = [0 if gamma_all['order_redone'][i]==gamma_all['label'][i] else 1 for i in range(gamma_all.shape[0])]
print('all:', gamma_all['rank_order_stimmt_redo'].value_counts())

all: rank_order_stimmt_redo
0    27722
1    20378
Name: count, dtype: int64

In [33]:
per_order_gamma = gamma_all.groupby("label").agg(
    n=("score", "size"),
    n_misclassified=("rank_order_stimmt", "sum"),
    n_rescued=("rank_order_stimmt_redo", 
                lambda x: ((gamma_all.loc[x.index, "rank_order_stimmt"] == 1) & 
                            (x == 0)).sum()),
    n_damaged=("rank_order_stimmt_redo", 
                lambda x: ((gamma_all.loc[x.index, "rank_order_stimmt"] == 0) & 
                            (x == 1)).sum()),
)
per_order_gamma["net"] = per_order_gamma["n_rescued"] - per_order_gamma["n_damaged"]
per_order_gamma["original_error_rate"] = per_order_gamma["n_misclassified"] / per_order_gamma["n"]
per_order_gamma["new_error_rate"] = (per_order_gamma["n_misclassified"] - per_order_gamma["n_rescued"] 
                                + per_order_gamma["n_damaged"]) / per_order_gamma["n"]
print("Denoising\n", per_order_gamma.sort_values("label", ascending=True))

Denoising
                    n  n_misclassified  n_rescued  n_damaged  net  \
label
Araneae          564             32.0          6          6    0
Blattodea         23             15.0          4          0    4
Coleoptera      1143            443.0         61         86  -25
Diptera        31914           8197.0        925       1766 -841
Hemiptera        775            539.0         51         45    6
Hymenoptera     3326           1578.0        117        279 -162
Ixodida            1              1.0          0          0    0
Lepidoptera     1744             98.0         31         13   18
Mecoptera         34             31.0          2          1    1
Neuroptera       115            107.0          0          0    0
Orthoptera         8              0.0          0          0    0
Plecoptera        54             12.0          1          6   -5
Raphidioptera      2              0.0          0          1   -1
Trichoptera       85              2.0          2          8   -6

               original_error_rate  new_error_rate
label
Araneae                   0.056738        0.056738
Blattodea                 0.652174        0.478261
Coleoptera                0.387577        0.409449
Diptera                   0.256847        0.283199
Hemiptera                 0.695484        0.687742
Hymenoptera               0.474444        0.523151
Ixodida                   1.000000        1.000000
Lepidoptera               0.056193        0.045872
Mecoptera                 0.911765        0.882353
Neuroptera                0.930435        0.930435
Orthoptera                0.000000        0.000000
Plecoptera                0.222222        0.314815
Raphidioptera             0.000000        0.500000
Trichoptera               0.023529        0.094118

In [34]:
per_order_gamma.to_csv("/Users/krolik/Downloads/Thesis/detailed_sample_description/rescue_damage_gamma.csv")

# Preprocessing details

In [42]:
TECHNIQUE_SPECS = {
    "unsharp_mask": {
        "target_property": "edge_density",
        "direction":       "low",
        "rationale":       "Enhances local edge contrast → directly targets low edge_density images "
                           "(the strongest Model 2 protective predictor)",
    },
    "clahe": {
        "target_property": "dynamic_range",
        "direction":       "low",
        "rationale":       "Increases local contrast → targets low dynamic_range images",
    },
    "denoise": {
        "target_property": "blur_score",
        "direction":       "high",
        "rationale":       "Removes noise → targets high blur_score (high Laplacian variance "
                           "= noise indicator in Model 2)",
    },
    "bilateral": {
        "target_property": "shadow",
        "direction":       "high",
        "rationale":       "Edge-preserving smooth lifts shadows → targets shadow-flagged images",
    },
    "white_balance": {
        "target_property": "colorfulness",
        "direction":       "low",
        "rationale":       "Neutralises colour casts → targets low colourfulness images",
    },
    "auto_contrast": {
        "target_property": "overexposed_pct",
        "direction":       "high",
        "rationale":       "Histogram stretching → targets overexposed images",
    },
    "gamma": {
        "target_property": "brightness_mean",
        "direction":       "low",
        "rationale":       "Brightens midtones → targets dark images",
    },
}

In [40]:
def apply_clahe(img):
    """For low brightness_std (low contrast)."""
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    return cv2.cvtColor(cv2.merge((clahe.apply(l), a, b)), cv2.COLOR_LAB2BGR)

def apply_white_balance(img):
    """Gray-world white balance, for color casts (twilight, low colorfulness)."""
    img_f = img.astype(np.float32)
    means = img_f.reshape(-1, 3).mean(axis=0)
    gray = means.mean()
    # Avoid division by zero on near-black channels
    means_safe = np.where(means < 1, 1, means)
    img_f = img_f * (gray / means_safe)
    return np.clip(img_f, 0, 255).astype(np.uint8)

def apply_auto_contrast(img):
    """For over/underexposed images. PIL autocontrast with 1% cutoff."""
    pil = Image.fromarray(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    return cv2.cvtColor(np.array(ImageOps.autocontrast(pil, cutoff=1)),
                        cv2.COLOR_RGB2BGR)

def apply_unsharp_mild(img):
    """Milder: smaller amplitude."""
    blurred = cv2.GaussianBlur(img, (0, 0), sigmaX=2)
    return cv2.addWeighted(img, 1.25, blurred, -0.25, 0)  # amount=0.25

def apply_unsharp_current(img):
    """Current: original setting."""
    blurred = cv2.GaussianBlur(img, (0, 0), sigmaX=2)
    return cv2.addWeighted(img, 1.5, blurred, -0.5, 0)  # amount=0.5

def apply_unsharp_aggressive(img):
    """More aggressive: larger amplitude, broader sigma."""
    blurred = cv2.GaussianBlur(img, (0, 0), sigmaX=3)
    return cv2.addWeighted(img, 2.0, blurred, -1.0, 0)  # amount=1.0

def apply_gamma(img, gamma=1.2):
    """For brightness imbalance. gamma > 1 brightens shadows."""
    inv = 1.0 / gamma
    table = np.array([((i / 255.0) ** inv) * 255 for i in range(256)]).astype(np.uint8)
    return cv2.LUT(img, table)

def apply_bilateral(img):
    """For shadow effects; edge-preserving smooth lifts midtones."""
    return cv2.bilateralFilter(img, d=9, sigmaColor=75, sigmaSpace=75)

def apply_denoise(img):
    """For noisy (night) images. Non-Local Means denoising."""
    return cv2.fastNlMeansDenoisingColored(img, None,
                                            h=10, hColor=10,
                                            templateWindowSize=7,
                                            searchWindowSize=21)